### PR TITLE
Re-apply copyright notice to license file

### PR DESCRIPTION
**Pull request by jasnell**
The text update inadvertently removed the copyright

### CODE REVIEW

**Comment by dankohn** [comment]
Actually, adding the copyright there will likely cause GitHub's licensee library not to be able to recognize it has Apache. Here's our recommendation on copyright notice: https://github.com/cncf/foundation/blob/master/copyright-notices.md.

You could also add to the Readme that all code as of yesterday was copyright HSE, but going forward it will be copyright "The COVID Green Authors" as you start accepting contributions from people not affiliated with HSE.

**Comment by jasnell** [comment]
Once we actually start receiving contributions from external I will add the additional copyright notice. It's unfortunate that GitHub's licensee library is not able to recognize the normative way that the Apache v2.0 license indicates it's license should be applied, but that's for a separate conversation.

**Comment by dankohn** [comment]
You could also just add the HSE copyright info to the Readme.

**Comment by jasnell** [comment]
Yeah, I'll do that in a bit :-)

**Comment by jasnell** [comment]
Closing in favor of #6

**Pull request closed without merging**
